북마크 조회 기능
ootd-zip/server pull request #120
Opened 2024-02-20 03:19 UTC by jinhoon227

## 변경사항
- 북마크 전체 조회 기능 추가
- 북마크 1개 이상 삭제 기능 추가
- 위 기능에 대한 테스트 추가
- OotdGetRes 에서 기존에있는 BrandDto, DetailCategory 로 사용

close #119

2024-02-20 12:30 UTC, kkmin223 requested changes

2024-02-20 12:30 UTC, kkmin223 commented on src/main/java/zip/ootd/ootdzip/ootdbookmark/data/OotdBookmarkGetAllRes.java
> +        this.ootdId = ootdBookmark.getOotd().getId();
저는 생성자 바로 쓰는것 보다는 팩토리 메소드로 만들어서 쓰는게 더 좋을 것 같아요

2024-02-20 13:46 UTC, jinhoon227 commented on src/main/java/zip/ootd/ootdzip/ootdbookmark/controller/OotdBookmarkController.java
> +        ootdBookmarkRepository.deleteAllById(request.getOotdBookmarkIds());
service 로 이동되었습니다!

2024-02-20 14:04 UTC, jinhoon227 commented on src/main/java/zip/ootd/ootdzip/ootdbookmark/data/OotdBookmarkGetAllRes.java
> +        this.ootdId = ootdBookmark.getOotd().getId();
@Lechros  @kkmin223 

DTO 를 어떤방식으로 생성할지 회의가 필요해보입니다.

1. 생성자기반 DTO 생성
2. 정적팩토리메서드
3. 정적팩토리메서드+Builder

2024-02-20 14:38 UTC, kkmin223 commented on src/main/java/zip/ootd/ootdzip/ootdbookmark/data/OotdBookmarkGetAllRes.java
> +        this.ootdId = ootdBookmark.getOotd().getId();
가장 많이 쓰이는게 3번 같아요
생성자는 private으로 막고 빌더 사용 & 정적 팩토리 메소드 사용

2024-02-21 02:12 UTC, kkmin223 approved these changes
승인합니다

2024-02-21 04:46 UTC, merged