Feature/thumbnail(#227)
ootd-zip/server pull request #233
Opened 2024-06-15 03:15 UTC by jinhoon227

## 변경사항
- 로딩속도, 데이터다운량 개선을 위해 썸네일을 추가로 s3 에저장합니다.

## 참고사항

### 썸네일 저장 방식
썸네일 저장 방식으로 크게 3가지를 생각했습니다.
1. DB 에 별도의 image 테이블을 만들어 조회시 조인을 사용
2. @Embeddable Image 클래스를 만들어서 사용(DB 에서는 조인을 할필요없이 같은 컬럼에 추가로 생성)
3. DB 에 테이블을 만들지 않고 조회시 기본링크를 수정하여 사용

1 번의 경우 조인 비용이 크고, 3번의 경우 유지보수 할 때 조금 불편할 수 있고 링크 수정시 사용되는 matcher 비용도 있기에 절충하여 2번을 선택했습니다. 2번의 경우 조인도 matcher 도 사용하지 않기에 좀 더 성능의 이점이 있고, 클래스로 관리할 수 있다는 장점이 있습니다. 단점으로는 1,2번은 DB 에도 컬럼을 추가해야되기에 마이그레이션 할 때 좀 더 힘듭니다.

### 이미지 리사이즈 방식
기존 이미지를 리사이즈해서 썸네일을 저장합니다.  리사이즈 하는 라이브러리의 종류는 여러개 있지만 `thumbnailtor` 를 선택했습니다. 이는 다른 라이브러리에 비해 속도 중간, 리사이즈된 사진 퀄리티 중간 정도를 가집니다. [비교글](https://wildeveloperetrain.tistory.com/289)을 참고했습니다.

### 썸네일 저장 로직
현재 사진 로직은 다음과 같습니다.
1. 프론트에서 s3 에 사진 저장 요청
2. 백엔드에서 s3 사진 저장후 프론트에 해당 이미지 url 반환
3. 프론트에서 해당 url 과 다른 정보와 함께 백엔드에 ootd/의류/유저프로필 등록 요청

이 과정에서 1-2 번 과정에서 백엔드는 사진을 s3 하는데 시간이 걸리고, 썸네일 변환작업까지 시간이 걸리는데 이는 유저에게 굉장히 많은 대기 시간을 요구합니다. 그래서 이를 비동기를 처리하여 성능을 개선했습니다. 개선된 로직은 다음과 같습니다.

1. 프론트에서 s3 에 사진 저장 요청
2. 백엔드에서 바로 이미지 url 반환(사진이 저장되지 않은 상태지만 먼저 url 을 반환합니다.)
3. 프론트 내부에서 자체적으로 이미지를 사용자에게 보여줌
4. 백엔드에서 비동기로 이미지 저장(+ 썸네일 사진 변환해서 추가 저장)
5. 프론트에서 해당 url 과 다른 정보와 함께 백엔드에 ootd/의류/유저프로필 등록 요청

이렇게 사용자는 대기시간 없이 사진을 바로볼 수 있습니다. 그리고 무조건 사용자가 올린 사진을 s3 에 저장했어야 됬는데 해당로직을 사용하면 필요한 사진만 저장합니다.(예를 들어 사용자가 단순히 사진을 올리고 OOTD 를 등록하지 않아도 사진은 s3 에 저장됬었는데 이젠 그렇지않습니다)

단점으로는 일단 이미지 저장이 성공하든 실패하든 사용자에게 url 을 반환합니다. 일반적으로 발생하는 상황이 아니고, 유저편의성을 생각하면 이점이 더 크다고 생각합니다. 추후에는 개선이 필요해보입니다.

close #227

2024-06-15 10:16 UTC, kkmin223 requested changes
이미지를 업로드하기전에 사용자에게 응답을 주는만큼 들어온 파일이 이미지가 맞는지 검사하는 과정과 s3 업로드 실패 시 재시도하는 로직이 들어가면 좋을것 같습니다!

2024-06-15 10:16 UTC, kkmin223 commented on src/main/java/zip/ootd/ootdzip/images/service/ImagesAsyncService.java
s3 업로드를 실패했을때 재시도하는 로직을 넣으면 어떨까요?

2024-06-15 10:16 UTC, kkmin223 commented on src/main/java/zip/ootd/ootdzip/images/service/ImagesService.java
> +
들어온 파일이 이미지 파일이 맞는지 검사하는 로직도 필요할것 같습니다

2024-06-15 17:13 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/images/domain/Images.java
> +        String fileName = matcher.group(2) + "_" + width + "x" + height;
suggestion: 썸네일의 크기나 파일명 규칙 구현이 Async 클래스와 중복되는데 하나의 클래스에서 관리하면 좋을 거 같아요.

2024-06-15 17:13 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/images/domain/Images.java
> +        String regex = "(https://ootdzip.*?/)(.*?)(\\.png)";
question: Async 클래스 구현에서는 `FILE_EXTENSION`이 `.jpg`로 설정되어 있는데 괜찮을까요?

2024-06-16 02:38 UTC, jinhoon227 commented on src/main/java/zip/ootd/ootdzip/images/domain/Images.java
> +        String regex = "(https://ootdzip.*?/)(.*?)(\\.png)";
베리굿

2024-06-16 03:28 UTC, kkmin223 approved these changes

2024-06-16 08:38 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/user/domain/User.java
> +    private Images images;
issue: 변수명에 profile은 유지하는게 좋지 않을까요?

2024-06-16 08:56 UTC, jinhoon227 commented on src/main/java/zip/ootd/ootdzip/user/domain/User.java
> +    private Images images;
지금 서비스상 유저의 이미지나 유저의 프로필 이미지는 같은 의미이기때문에, 다른 클래스랑 동일하게 변수명을 맞추는게 낫다고 판단했습니다.

2024-06-17 06:15 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/common/exception/code/ErrorCode.java
> +    IMAGE_UPLOAD_FAIL(400, "I003", "이미지 업로드를 했습니다."),
실패가 없어요!!!

2024-06-17 06:17 UTC, jinhoon227 commented on src/main/java/zip/ootd/ootdzip/common/exception/code/ErrorCode.java
> +    IMAGE_UPLOAD_FAIL(400, "I003", "이미지 업로드를 했습니다."),
굳

2024-06-17 06:17 UTC, Lechros approved these changes
수고하셨어요! S3 업로드 잘 되기를 기도합니다...

2024-06-17 06:17 UTC, merged