feat: 옷 저장 로직 추가
ootd-zip/server pull request #25
Opened 2023-08-07 13:33 UTC by kkmin223

## 변경 내용
1. 옷 관련 엔티티, 레퍼지토리, 서비스 추가
2. 테스트케이스 추가

## 추가 필요한 내용
1. S3 연결 필요

## 논의 필요한 부분
1. Color, Category, Style 엔티티는 OOTD 작성, 유저가 선호하는 카테고리, 스타일을 저장할 때 같이 사용하는 방향으로 할 지
2. 옷 저장 성공 시 Response에 저장된 내용을 반환해 줄 지, 저장된 고유 id만 반환해 줄 지

close #8

2023-08-09 08:41 UTC, Lechros requested changes
리뷰 단 파일 외에도 간격 추가해주세요.

2023-08-09 08:41 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/brand/domain/Brand.java
> +    private String name;
컬럼 사이에 공백 추가해주세요.

2023-08-09 08:41 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/category/domain/Category.java
> +@Table(name = "categoies")
`categoies` -> `categories`

2023-08-09 08:41 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/category/domain/Category.java
> +    private Long id;
특별한 이유가 없으면 BaseEntity 상속받는게 좋아보여요. (Category, Color, Style)

2023-08-09 08:41 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/category/domain/Color.java
> +    private Long id;
사이에 공백!

2023-08-12 15:12 UTC, kkmin223 commented on src/main/java/zip/ootd/ootdzip/category/domain/Category.java
> +    private Long id;
Category, Color, Style은 관리자가 입력하고, 수정이 많이 일어날것 같지 않고 삭제하게 된다면 soft delete가 아닌 데이터를 날려버리는 식으로 삭제할 텐데, createdAt, updatedAt이라는 데이터가 필요없다고 생각해서 상속받지 않았습니다!

모든 엔티티에 createdAt, updatedAt 해당 컬럼이 필요할지 생각해 봐야 할 것 같습니다!

2023-08-22 13:03 UTC, jinhoon227 requested changes

2023-08-22 13:03 UTC, jinhoon227 commented on src/main/java/zip/ootd/ootdzip/category/domain/Category.java
> +    @Enumerated(EnumType.ORDINAL)
EnumType.STRING 으로 변경해주세요!

2023-08-22 13:40 UTC, Lechros approved these changes

2023-08-22 13:40 UTC, jinhoon227 approved these changes
수고했습니다

2023-08-22 13:40 UTC, merged