test: 테스트 환경 설정
ootd-zip/server pull request #258
Opened 2024-11-10 12:17 UTC by kkmin223

- Test 프로필 분리
- Transactional 어노테이션 제거

2024-11-11 01:47 UTC, Lechros requested changes
`application-test.yaml`을 `test/resources` 경로로 옮기고 기존 설정과 동일한 내용은 변경하는게 좋을 것 같아요.

2024-11-11 02:15 UTC, Lechros commented on src/main/resources/application-test.yaml
> +  data:
question: 레디스 사용에 `spring.jpa.data.redis`와 `spring.data.redis` 둘 다 필요한가요?

2024-11-16 10:12 UTC, kkmin223 commented on src/main/resources/application-test.yaml
> +  data:
`spring.data.redis`만 필요한 것으로 확인해서 제거했습니다.

2024-11-17 04:33 UTC, Lechros commented
테스트에서만 사용되는 파일이므로 테스트 리소스로 옮기는 건 어떻게 생각하시나요?

2024-11-17 05:36 UTC, kkmin223 commented
> 테스트에서만 사용되는 파일이므로 테스트 리소스로 옮기는 건 어떻게 생각하시나요?

test 하단에 resource로 옮겼습니다~

2024-11-17 11:12 UTC, Lechros approved these changes
LGTM (폰이라 커밋이 제대로 안보였었나봐요.)

2024-11-17 12:54 UTC, merged