Feature/google login register
ootd-zip/server pull request #31
Opened 2023-08-19 06:49 UTC by jinhoon227

## 변경 내용
1. 구글 로그인, 회원가입 관련 로직 추가
2. 카카오 구글 추상화 리팩토링

## 참고할 내용
1. 구글 키설정 파일은 깃허브에 올리지 않았습니다.
2. feature/security 를 풀 한다음 추가로 작업을 하였습니다.

## 논의 필요한 부분
1. 예외처리에 관하여 코드도 글로벌하게 가져갈지 패키지별로 가져갈지 논의가 필요해 보입니다.

close #19

2023-08-20 13:56 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/common/exception/CustomException.java
> +public class CustomException extends RuntimeException {
`CustomException`에 `ErrorCode`를 받는 것보다 로그인 에러 클래스를 만들어 divisionCode로 분류하고 세부 내용을 메시지에 전달하면 좋을 것 같아요.

2023-08-20 13:56 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/oauth/data/GoogleOauthToken.java
> +    private String access_token;
style: 사이에 간격 추가 부탁드려요!! 다른 파일도 Format 한번씩만 해주세요. (EOF 전에 엔터가 없는 파일이 있어요)

2023-08-20 13:56 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/oauth/domain/OauthProvider.java
> +    KAKAO, GOOGLE,
style: 각각의 라인에 적는 것이 더 좋아보여요.

2023-08-20 13:56 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/oauth/domain/RefreshToken.java
> +    private User user;
TODO : `@JoinColumn` 어노테이션 추가해야 합니다.

2023-08-20 13:56 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/oauth/service/GoogleOAuthUtils.java
> +    @Value("${spring.security.oauth2.client.registration.google.client-id}")
저는 `@Value` 어노테이션을 private 필드에 적용해두면 테스트할 때 설정하기 어려워서 생성자에 설정해뒀는데 혹시 고려하신 부분일까요?

2023-08-20 13:56 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/oauth/service/GoogleOAuthUtils.java
> +        headers.add("Authorization", "Bearer " + accessToken);
`setBearerAuth` 메소드 사용하면 더 간결하게 설정돼요!

2023-08-20 13:56 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/user/service/UserService.java
> +    private SocialOAuth findSocialOauthByType(OauthProvider oAuthProvider) {
OauthUtils를 OauthService로 변경하고 알맞은 impl을 관리하고 반환하는 별도의 클래스를 만들고, appContext.getBean(...)로 인스턴스를 관리하는게 훨씬 깔끔해 보입니다. interface의 default type()도 제거할 수 있겠네요.
이 부분은 머지되고 제가 따로 리팩토링할게요.

2023-08-20 13:56 UTC, Lechros commented on src/main/resources/application.yaml
> +    url: jdbc:mariadb://localhost:3307/ootdzip
3306으로 되돌려주세요~~!

2023-08-20 14:56 UTC, kkmin223 requested changes

2023-08-20 14:56 UTC, kkmin223 commented on src/main/java/zip/ootd/ootdzip/oauth/domain/UserAuthenticationToken.java
> +        return null;
해당 부분은 구현할 예정인건가요?
원래 null을 리턴하는 걸까요?

2023-08-20 14:56 UTC, kkmin223 commented on src/main/java/zip/ootd/ootdzip/oauth/service/GoogleOAuthUtils.java
> +        }
이 부분 try catch를 안쓰고 throw만 하면 에러 핸들링 되는거 아닌가요?
GlobalExceptionHandler에서 처리 못하나요?

2023-08-20 14:56 UTC, kkmin223 commented on src/main/java/zip/ootd/ootdzip/user/domain/User.java
> +@Setter
Entity에서는 Setter를 지양하는 것이 좋을 것 같은데 추가한 이유가 있을까요?

2023-08-20 14:56 UTC, kkmin223 commented on src/main/java/zip/ootd/ootdzip/user/controller/UserController.java
> +        response.addCookie(cookie);
해당부분 함수로 빼는것도 좋을 것 같습니다.

2023-08-20 14:56 UTC, kkmin223 commented on src/main/resources/application.yaml
> +    url: jdbc:mariadb://localhost:3307/ootdzip
돌려주세요

2023-08-20 15:52 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/oauth/domain/UserAuthenticationToken.java
> +        return null;
아마도 Role 추가할 때 사용되는 부분으로 알고 있어요. 저희는 사용 안하니까 null 반환해요.

2023-08-22 12:46 UTC, Lechros approved these changes

2023-08-22 12:47 UTC, merged