Feature/get board
ootd-zip/server pull request #53
Opened 2023-10-20 08:01 UTC by jinhoon227

## 변경 내용
1. 게시판 OOTD 글 단건 조회, 전체 조회기능 추가
2. 게시판 좋아요 추가/취소 기능 추가
3. 게시판 북마크 추가/취소 기능 추가

## 참고 사항
1. 게시판 글의 조회수, 좋아요 수, 좋아요여부를 Redis 에 저장합니다. 
조회할때, Redis 조회 후 데이터가 없을시 DB 에 접근해서 조회합니다. Redis 에서 userId 로 추가적으로 저장하여 중복 조회수, 중복 좋아요 수 카운트를 방지했습니다.
2. Redis 저장 된 데이터를 DB 에 저장하는 로직은 아직 없습니다. 추후 개발 예정입니다.

구체적인 redis 저장 전략은 다음과 같습니다.
- getView : redis 에 조회수가 저장되어있으면 반환, 없으면 entity 에서 조회수를 가져와 redis에 저장 후 조회수 반환 
- countView : redis 에 해당하는 유저가 조회한적이 있는지 확인후, 조회한적이 없다면 카운트
- getLike : redis 에 좋아요수가 저장되어있으면 반환, 없으면 entity 에서 좋아요수를 가져와 redis에 저장 후 좋아요 수 반환
- countLikeInRedis : 유저가 좋아요시 redis 에 있는 좋아요 수 증가
- discountLikeInRedis : 유저가 좋아요 취소시 redis 에 있는 좋아요 수 감소
- getUserLike : redis 에 유저가 좋아요를 한 기록이 저장되어있으면 반환, 없으면 entity 에서 유저의 좋아요 여부 가져와 redis에 저장 후 좋아요 여부 반환
- addUserLikeInRedis : redis 에 좋아요 여부 추가
- cancelUserLikeInRedis : redis 에 좋아요 여부 삭제

close #12

2023-10-21 08:09 UTC, kkmin223 requested changes
서비스 로직에서 함수를 만든 의도?, 설명?을 주석으로 추가해주면 더 이해하기 쉬울것 같습니다.

2023-10-21 08:09 UTC, kkmin223 commented on src/main/java/zip/ootd/ootdzip/boardbookmark/domain/BoardBookmark.java
> +    private boolean isBookmark = false;
BoardLike와 같은 이유로 isBookmark가 왜 필요할까요?

2023-10-21 08:09 UTC, kkmin223 commented on src/main/java/zip/ootd/ootdzip/board/service/BoardService.java
> +        Board board = boardRepository.findById(request.getBoardId()).orElseThrow();
단건 조회 했을 때는 isPublic, isDeleted, reportCount 조건을 제외한 이유가 있을까요?

2023-10-21 08:09 UTC, kkmin223 commented on src/main/java/zip/ootd/ootdzip/board/service/BoardService.java
> +        List<Board> boards = boardRepository.findOotdAll();
해당 쿼리에서 isPublic이 true인 것만 조회하고 있는데, 
작성자 본인이 조회했을 때는 isPublic 관계없이 조회가 되야하지 않을까요?

2023-10-21 08:09 UTC, kkmin223 commented on src/main/resources/application.yaml
> +    username: root
이거 되돌려주세요...

2023-10-22 06:08 UTC, jinhoon227 commented on src/main/java/zip/ootd/ootdzip/board/service/BoardService.java
> +        Board board = boardRepository.findById(request.getBoardId()).orElseThrow();
1. 맨 처음 게시글 전체 조회
2. 사용자가 클릭한 게시글 단건 조회

단건조회 로직은 전제조건으로 게시글 전체 조회 후에 단건조회가 발생한다고 생각했습니다. 전체 조회에서 이미 isPublic, isDeleted, reportCount 조건을 고려했기 때문에, 단건조회에서는 고려하지 않았습니다. 

생각해보니 전체조회와 단건조회에도 시간차가 존재하기때문에 조건을 넣는게 좋다고 생각됩니다.

2023-10-22 06:18 UTC, jinhoon227 commented on src/main/java/zip/ootd/ootdzip/board/service/BoardService.java
> +        List<Board> boards = boardRepository.findOotdAll();
전체 조회는 "모든 사람이 보는 공간" 이기 때문에 `isPublic` 이 false 이면 본인글도 조회되지 않습니다.

 단건조회의 경우에서도 `isPublic` 이 false 여도 본인이면 조회가 가능한 로직을 만들려면 BoardUser, User 엔티티를 추가로 조회해야됩니다. 그러니 본인글 단건조회할때와, 일반적인 단건조회 db 요청을 나누는게 낫다고 판단됩니다.
 => 해결방법으로 본인글 단건조회할때는 `isPublic` 조건 상관없이 조회되는 로직을 추가했습니다.

2023-10-22 12:27 UTC, Lechros commented
`BoardOotd`, `OotdBoard`, `Ootd` 네이밍을 통일시키거나 규칙을 만들어야 할 것 같습니다.

2023-10-22 13:04 UTC, Lechros requested changes

2023-10-22 13:04 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/board/repository/BoardRepository.java
> +    List<Board> findOotdAll(); // 역순
기본 동작은 public을 무시하고, public이 아닌 것만 가져오는 메소드가 특별한 경우인 경우가 맞을 것 같습니다.

2023-10-22 13:04 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/board/repository/BoardRepository.java
> +    Optional<Board> findOotd(@Param(value = "boardId") Long boardId);
기본 동작은 public을 무시하고, public이 아닌 것만 가져오는 메소드가 특별한 경우인 경우가 맞을 것 같습니다. Service 단에서 검사하거나 Board.isVisible(user) 등으로 책임을 외부로 위임하는 방식으로요.

2023-10-23 07:08 UTC, jinhoon227 commented on src/main/java/zip/ootd/ootdzip/board/service/BoardService.java
> +    private void countLikeInRedis(Board board, User user) {
조회시 좋아요 여부를 검사해서, `countLikeInRedis` 에서  `getUserLike` 를 호출해 중복검사를 한다고 볼 수 있습니다. 하지만 조회후, 스케줄러가 redis 에서 db에 넣으면서 redis 를 비워버리고 `countLikeInReids` 를 호출시에도 정상적인 작동을 위해서 중복검사를 허용했습니다.

명확한 스케줄러 정책이 아직 정해지지 않았기때문에 지금은 중복검사를 하는 방향으로 갈려고합니다.

2023-10-23 12:08 UTC, Lechros reviewed
nitpick 좀 했습니다.

2023-10-23 12:08 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/ootd/domain/Ootd.java
> +    private boolean isPublic;
isPrivate를 저장하는게 자연스러워 보이는데 어떠신가요?

2023-10-23 12:21 UTC, jinhoon227 commented on src/main/java/zip/ootd/ootdzip/ootd/domain/Ootd.java
> +    private boolean isPublic;
천잰데요?

2023-10-23 13:41 UTC, kkmin223 approved these changes
승인이욥

2023-10-23 14:39 UTC, Lechros approved these changes
private 잘 변환하셨고 findAllByUserId로 바꾸셨군요 좋습니다!

2023-10-24 06:10 UTC, merged