Feature/#16
ootd-zip/server pull request #56
Opened 2023-10-23 13:43 UTC by kkmin223

## 변경사항
1. 옷 저장 로직 수정(기존에 DB Insert를 안하고 있어서 수정했습니다)
2. 옷 삭제 API 및 서비스 로직 추가
      - 옷 삭제도 soft delete 해야할 지 확인 필요할 것 같습니다.

2023-10-24 06:29 UTC, jinhoon227 requested changes

2023-10-24 06:29 UTC, jinhoon227 commented on src/main/java/zip/ootd/ootdzip/clothes/domain/Clothes.java
> +    private List<BoardClothes> boardClothesList = new ArrayList<>();
Board -> Ootd 로 변경되었습니다! main 에 해당 변경사항 머지되어있으니 충돌안나게 잘 합쳐주세요

2023-10-26 14:06 UTC, kkmin223 commented on src/main/java/zip/ootd/ootdzip/clothes/domain/Clothes.java
> +    private List<BoardClothes> boardClothesList = new ArrayList<>();
main이랑 머지 완료 했습니다~!

2023-10-26 14:08 UTC, jinhoon227 approved these changes
승인합니다!

2023-10-27 18:24 UTC, Lechros requested changes

2023-10-27 18:24 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/clothes/service/ClothesServiceImpl.java
> +                .orElseThrow(() -> new IllegalArgumentException("유효하지 않은 옷 ID"));
`IllegalArgumentException`은 400을 반환하는 것으로 아는데 id에 해당하는 옷이 존재하지 않는 상황이므로 404를 반환하는 것이 적절해 보여요.

2023-10-28 12:30 UTC, kkmin223 commented on src/main/java/zip/ootd/ootdzip/clothes/service/ClothesServiceImpl.java
> +                .orElseThrow(() -> new IllegalArgumentException("유효하지 않은 옷 ID"));
NOT_FOUND_ERROR 404로 변경했습니다!

2023-10-28 17:14 UTC, Lechros approved these changes
좋습니다!

2023-10-28 17:41 UTC, merged