Feature/save redis to db
ootd-zip/server pull request #57
Opened 2023-10-27 10:01 UTC by jinhoon227

## 변경 내용
1. Redis 에 저장된 조회수를 DB 에 저장합니다.

## 참고 사항

**현재 조회수만 저장하는 로직만 구현되어있으며, 리뷰에서 문제없을시 비슷한 방식으로 좋아요 저장로직도 구현할 예정입니다.**

2023-10-27 18:17 UTC, Lechros requested changes
1. RedisKey 네이밍
  `VIEW`->`VIEWS`, `UPDATED_VIEW`->`UPDATED_VIEWS`, `LIKE`->`LIKES` 처럼 복수형을 사용하거나 COUNT를 붙이는 것이 개수라는 의미가 더 잘 전달될 것 같아요.
2. RedisDao 네이밍
  `setValues` 등 한 개의 값만 설정하는 함수들에 복수형이 사용되어 있어요. 특별한 이유가 없다면 새로운 PR 만들어서 적절한 동사/단수형으로 수정할게요.

2023-10-27 18:17 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/ootd/scheduler/OotdScheduler.java
> +        String filterKey = RedisKey.VIEW.makeFilterKeyWith(ootd.getId());
question: filterKey가 무엇인가요?

2023-10-28 12:46 UTC, kkmin223 requested changes
전 updateViewCount에 중복 로직부문 만 수정해주시면 될것 같아요!

2023-10-28 12:46 UTC, kkmin223 commented on src/main/java/zip/ootd/ootdzip/ootd/scheduler/OotdScheduler.java
> +     * 애플리케이션 시작 후 30초 후에 첫 실행, 그 후 매 10초마다 주기적으로 실행(바뀔예정)
스케줄러를 애플리케이션 시작 후가 아닌 특정 시간대를 지정할 수 있나요?

2023-10-28 12:46 UTC, kkmin223 commented on src/main/java/zip/ootd/ootdzip/ootd/scheduler/OotdScheduler.java
> +            sliceOotds.get().forEach(this::updateViewCountRedisToDB);
저도 이부분은 동일한 로직으로 보입니다. 같은 로직이라면 동일한 방식으로 바꿔주세요
그리고 해당 부분은 do while문을 사용하면 이러한 문제를 풀 수 있을것 같아요!

2023-10-30 08:11 UTC, jinhoon227 commented on src/main/java/zip/ootd/ootdzip/ootd/scheduler/OotdScheduler.java
> +     * 애플리케이션 시작 후 30초 후에 첫 실행, 그 후 매 10초마다 주기적으로 실행(바뀔예정)
특정 시간대 지정도 가능합니다

2023-10-30 08:13 UTC, jinhoon227 commented on src/main/java/zip/ootd/ootdzip/ootd/scheduler/OotdScheduler.java
> +        String filterKey = RedisKey.VIEW.makeFilterKeyWith(ootd.getId());
filterKey 는 동일한 사용자의 중복을 조회수 증가를 막기위함입니다.
filterKey 에는 사용자의 Id 가 저장됩니다. 조회수 증가를 하기전에 filterKey 에서 동일한 사용자가 있다면 최근에 조회를 했다는 뜻이므로 조회수를 상승시키지 않습니다.

2023-11-04 09:22 UTC, Lechros approved these changes
전 이제 OK입니다 고생하셨어요

2023-11-05 05:55 UTC, kkmin223 approved these changes
승인합니다~!

2023-11-05 06:10 UTC, merged