닉네임 중복 확인 API
ootd-zip/server pull request #68
Opened 2023-11-15 14:47 UTC by Lechros

2023-11-17 06:50 UTC, jinhoon227 requested changes
중복된 닉네임체크인데 Name 이 아니라 Id 라고 표현한 메서드명이나 api 명이 있는데 이를 바꿨으면 합니다!

2023-11-17 06:50 UTC, jinhoon227 commented on src/main/java/zip/ootd/ootdzip/user/service/UserService.java
> +    public boolean checkId(String name) {
중복확인 할려는게 name 이라면 함수명을 `checkName` 으로 하는게 낫지않나요?

2023-11-17 06:50 UTC, jinhoon227 commented on src/main/java/zip/ootd/ootdzip/user/controller/UserController.java
> +    @GetMapping("/check-id")
/check-name
/{name}/check
로 바꾸는게 어떨까요?

2023-11-17 06:50 UTC, jinhoon227 commented on src/main/java/zip/ootd/ootdzip/user/controller/UserController.java
> +        if (userService.checkId(request.getNickname())) {
예외처리 하는 과정도 비즈니스 로직이라고 생각하는데, service 단에서 처리하는게 낫지 않을까요?

2023-11-19 11:38 UTC, Lechros commented on src/main/java/zip/ootd/ootdzip/user/service/UserService.java
> +    public boolean checkId(String name) {
공식 명칭이 결정되면 name이나 nickname으로 변경하겠습니다!

2023-11-19 13:08 UTC, kkmin223 requested changes

2023-11-19 13:08 UTC, kkmin223 commented on src/main/java/zip/ootd/ootdzip/user/controller/UserController.java
> +        if (userService.checkId(request.getNickname())) {
이게 중복 체크하는 API인데 false일 때 에러를 반환할 필요가 있을까요?
회원가입을 할 때 중복이면 에러겠지만, 이 API는 중복체크 목적이기에 중복이여도 에러가 아닌 false 값을 리턴해주면 될 것 같은데요

2023-11-29 08:09 UTC, jinhoon227 approved these changes
저는 승인이여!

2023-12-12 05:37 UTC, merged