Feature/#64
ootd-zip/server pull request #69
Opened 2023-11-19 13:10 UTC by kkmin223

# 변경사항
- Category, Style, Color 등 옷 입력에 필요한 데이터 조회 API 추가 했습니다.
- 해당 데이터를 직접 DB에 Insert 할 지, 입력하는 API를 만들지 확인 필요할 것 같습니다.

close #64

2023-11-20 07:02 UTC, jinhoon227 requested changes
네이밍이랑 로직설명을 추가하면 좋을것같습니다

2023-11-20 07:02 UTC, jinhoon227 commented on src/main/java/zip/ootd/ootdzip/category/service/CategoryService.java
> +public class CategoryService {
해당 로직에대한 설명을 주석으로 추가하면 좋을것같습니다!

2023-11-23 10:42 UTC, jinhoon227 approved these changes
승인합니다!

2023-11-23 12:47 UTC, Lechros approved these changes
좋습니다!
추후에 Category.parentCategoryId를 parentCategory로 바꾸면 쿼리 한 번 절약할 수 있어 보이네요

2023-11-23 13:05 UTC, merged